services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: ${PLUGIN_SLUG}_wp
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/${PLUGIN_SLUG}
      - ./.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.11
    container_name: ${PLUGIN_SLUG}_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: ${PLUGIN_SLUG}_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  wordpress_data:
  db_data: